### ISSUE TITLE
مشکل در خرید برنامه یونیتی

### ISSUE THREAD

**Issue by fazelit** [myketstore/myket-billing-unity-sample#3]
با سلام
من وقتی با android logcat خطا رو بررسی می کنم خطای زیر میده:
`08/20 12:35:39.718 21154 21293 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: ir.myket.billingclient.MyketIABPlugin
08/20 12:35:39.718 21154 21293 Error Unity java.lang.ClassNotFoundException: ir.myket.billingclient.MyketIABPlugin
08/20 12:35:39.718 21154 21293 Error Unity 	at java.lang.Class.classForName(Native Method)
08/20 12:35:39.718 21154 21293 Error Unity 	at java.lang.Class.forName(Class.java:536)
08/20 12:35:39.718 21154 21293 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08/20 12:35:39.718 21154 21293 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
08/20 12:35:39.718 21154 21293 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
08/20 12:35:39.718 21154 21293 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
08/20 12:35:39.718 21154 21293 Error Unity 	at android.os.Looper.loopOnce(Looper.java:230)
08/20 12:35:39.718 21154 21293 Error Unity 	at android.os.Looper.loop(Looper.java:319)
08/20 12:35:39.718 21154 21293 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
08/20 12:35:39.718 21154 21293 Error Unity Caused by: java.lang.ClassNotFoundException: ir.myket.billingclient.MyketIABPlugin
08/20 12:35:39.718 21154 21293 Error Unity 	... 9 more
08/20 12:35:39.718 21154 21293 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
08/20 12:35:39.718 21154 21293 Error Unity   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
08/20 12:35:39.718 21154 21293 Error Unity   at UnityEngine.AndroidJavaClass._
`

**Comment by fazelit** [comment]
ضمنا من از نسخه قدیمی بدون گرادل استفاده می کنم این خطا بالا نمیده ولی برای اندروید خودم که نسخه 14 هست خطای زیر میده:
`2024/08/20 19:16:34.635 20089 20089 Error IabHelper In-app billing error: Illegal state for operation (launchPurchaseFlow): IAB helper is not set up.
`
ولی برای ایمولیتور و اندروید های پایین مثلا اندروید 7 به درستی کار می کنه!

**Comment by fazelit** [comment]
این مشکل رو هم می ده:
`2024/08/20 21:30:53.309 11885 11885 Error [MyketAIB][Plugin] Exception running command on UI thread: IAB helper is not set up. Can't perform operation: launchPurchaseFlow
`
